---

# This set of tasks prepares TPC-H data for use with MonetDB

# Author: Panagiotis Koutsourakis <kutsurak@monetdbsolutions.com>


- name: Create TPC-H generator directory
  command: "rsync -r {{ download_dir }}/monetdb/tpch_gen/dbgen/ {{ tpch_gen_dir }}/"
  args:
    creates: "{{ tpch_gen_dir }}/Makefile"

- name: Compile TPC-H generator
  command: make
  args:
    chdir: "{{ tpch_gen_dir }}"
    creates: "{{ tpch_gen_dir }}/dbgen"

- name: Run TPC-H generator
  command: ./dbgen -f -s {{ scale_factor }}
  args:
    chdir: "{{ tpch_gen_dir }}"
    creates: "{{ tpch_gen_dir }}/region.tbl"

- name: Create TPC-H scripts directory
  command: "rsync -r {{ download_dir }}/monetdb/tpch_scripts/ {{ tpch_scripts_dir }}/"

- name: Create TPC-H data directory
  file:
    path: "{{ tpch_scripts_dir }}/SF-{{ db_name }}/data"
    state: directory

- name: Move TPC-H data to data directory
  copy:
    src: "{{ tpch_gen_dir }}/{{ item }}.tbl"
    dest: "{{ tpch_scripts_dir }}/SF-{{ db_name }}/data"
    remote_src: True
  with_items: "{{ table_names }}"

# - name: Change owner
#   file:
#     path: /home/exanest/monetdb/tpch_scripts/SF-{{ db_name }}/data
#     group: monetdb
#     recurse: yes

# - name: Delete original files
#   file:
#     path: "{{ tpch_gen_dir }}"/dbgen/{{ item }}
#     state: absent
#   with_items: "{{ table_files }}"

# - name: Load files in monetDB
#   command: ./sf_build.sh SF-{{ db_name }}
#   args:
#     chdir: /home/exanest/monetdb/tpch_scripts

- name: Stop database SF-{{ db_name }}
  command: monetdb stop SF-{{ db_name }}
  ignore_errors: yes

- name: Destroy database SF-{{ db_name }}
  command: monetdb destroy SF-{{ db_name }} -f
  ignore_errors: yes

- name: Create database SF-{{ db_name }}
  command: monetdb create SF-{{ db_name }}

- name: Release database SF-{{ db_name }}
  command: monetdb release SF-{{ db_name }}

- name: Create database schema
  command: mclient -d SF-{{ db_name }} {{ tpch_scripts_dir }}/tpch_schema.sql

- name: Load data in monetdb
  command: ./sf_build.sh SF-{{ db_name }}
  args:
    chdir: "{{ tpch_scripts_dir }}"
