---

# This set of tasks prepares TPC-H data for use with MonetDB

# Author: Panagiotis Koutsourakis <kutsurak@monetdbsolutions.com>


- name: Create TPC-H generator directory
  command: "rsync -r {{ download_dir }}/monetdb/tpch_gen/dbgen/ {{ tpch_gen_dir }}/"
  args:
    creates: "{{ tpch_gen_dir }}/Makefile"

- name: Compile TPC-H generator
  command: make
  args:
    chdir: "{{ tpch_gen_dir }}"
    creates: "{{ tpch_gen_dir }}/dbgen"

- name: Run TPC-H generator
  command: ./dbgen -f -s {{ scale_factor }}
  args:
    chdir: "{{ tpch_gen_dir }}"
    creates: "{{ tpch_gen_dir }}/region.tbl"

- name: Create TPC-H scripts directory
  command: "rsync -r {{ download_dir }}/monetdb/tpch_scripts/ {{ tpch_scripts_dir }}/"

- name: Create TPC-H data directory
  file:
    path: "{{ tpch_scripts_dir }}/SF-{{ db_name }}/data"
    state: directory

- name: Move TPC-H data to data directory
  copy:
    src: "{{ tpch_gen_dir }}/{{ item }}.tbl"
    dest: "{{ tpch_scripts_dir }}/SF-{{ db_name }}/data"
    remote_src: True
  with_items: "{{ table_names }}"

- name: Stop database SF-{{ db_name }}
  command: "{{ monetdb_bin_dir }}/monetdb stop SF-{{ db_name }}"
  register: stop_result
  failed_when: stop_result.get('stderr') and not ('no such database' in stop_result.stderr or 'database is not running' in stop_result.stderr)

- name: Destroy database SF-{{ db_name }}
  command: "{{ monetdb_bin_dir }}/monetdb destroy SF-{{ db_name }} -f"
  register: destroy_result
  failed_when: destroy_result.get('stderr') and not 'no such database' in destroy_result.stderr

- name: Create database SF-{{ db_name }}
  command: "{{ monetdb_bin_dir }}/monetdb create SF-{{ db_name }}"

- name: Release database SF-{{ db_name }}
  command: "{{ monetdb_bin_dir }}/monetdb release SF-{{ db_name }}"

- name: Create database schema
  command: "{{ monetdb_bin_dir }}/mclient -d SF-{{ db_name }} {{ tpch_scripts_dir }}/tpch_schema.sql"

- name: Load data in monetdb
  command: "./sf_build.sh SF-{{ db_name }}"
  args:
    chdir: "{{ tpch_scripts_dir }}"
