---

# This set of tasks prepares an exanest server. It assumes that the machine is
# already running

# Author: Panagiotis Koutsourakis <kutsurak@monetdbsolutions.com>

- name: Create user exanest
  remote_user: root
  user:
    name: exanest
    groups: wheel
    append: yes
    password: "{{ password }}"

- name: Add authorized ssh key
  remote_user: root
  authorized_key:
    user: exanest
    state: present
    key: "{{ lookup('file', item) }}"
  with_items:
    - ./files/public_key
    - "{{ personal_ssh_pubkey }}"

- name: Set up passwordless sudo
  remote_user: root
  copy:
    dest: /etc/sudoers.d/wheel
    content: "%wheel	ALL=(ALL)	NOPASSWD: ALL"
