---

# This set of tasks prepares an exanest server. It assumes that the machine is
# already running

# Author: Panagiotis Koutsourakis <kutsurak@monetdbsolutions.com>

- name: Create user exanest
  user:
    name: exanest
    groups: wheel
    append: yes
    password: "{{ password }}"

- name: Add authorized ssh key
  authorized_key:
    user: exanest
    state: present
    key: "{{ lookup('file', item) }}"
  with_items:
    - ./files/public_key
    - ~/.ssh/id_rsa.pub
