---
# This play prepares the monetdb server. It assumes that the machine is booted
# already. Also it should be run like:

# $ ansible-playbook prepapre_server.yml -k

# and it will ask for the root password. After this playbook, ansible should
# have passwordless ssh access.

# This playbook will install wget, create a user exanest (with the same
# password) and copy a public ssh key.

# This playbook assumes that the target runs CentOS 7. See this link:
# http://www.exanest.eu/wiki/index.php?title=QEMU_%2B_ARMv8_disk_image_instructions
# for more information.

- hosts: monetdb
  remote_user: root
  vars:
    password: $6$lP8E9dJdEmT/BmFb$w0Ta1MdadpIfKYDsXYWvb0ZsbWfGPh9kNPmNrnIlbkf7KcThdDQ5cc6yDCjJXzxJW3UhMEhC7nH58NzWILJ3U/
  tasks:
    - name: Install wget
      yum:
        name: wget
        state: latest
    - name: Create user exanest
      user: name=exanest groups=wheel append=yes password={{password}}
    - name: Add authorized ssh key
      authorized_key:
        user: exanest
        state: present
        key: "{{ lookup('file', './files/public_key') }}"
