---

# Example Ansible playbook for setting up the MonetDB benchmarks.

# Install MonetDB from source
#- hosts: atraf
  #roles:
#  - build_dependencies
  #- monetdb_checkout
  #- build_monetdb
  #- private_farm

# Install MonetDB from RPM, and TPC-H
#- hosts: tpc_h
  #roles:
  #- tpch_node

# Install MonetDB from source, and the Air Traffic benchmark
# (We haven't packaged the latest MonetDB for exanest yet)
- hosts: atraf
  roles:
  - atraf_node
