- name: Create download dir
  file:
    path: "{{download_dir}}"
    state: directory

- name: Read atraf subset
  when: atraf_subset is defined
  command: "sed -e 's/ .*//' subsets/{{atraf_subset}}/inputs.txt"
  delegate_to: localhost
  register: atraf_inputs

- name: Create download dir Makefile
  template:
    src: Makefile.in
    dest: "{{download_dir}}/Makefile"

- name: Initial download {{download_dir_items}}
  #when: not not download_dir_items
  command: "make -C {{download_dir | escape}} {{item}}"
  register: download_result
  changed_when: not 'Nothing to be done for' in download_result.get('stdout','')
  with_items: "{{ download_dir_items }}"
