---

- name: "Create {{download_dir}}"
  file:
    path: "{{download_dir}}"
    state: directory

- name: Fetch MonetDB binary packages
  get_url:
    url: "{{packages_url}}"
    dest: "{{download_dir}}/{{packages_url | basename}}"

- name: Unpack MonetDB package files
  unarchive:
    remote_src: yes
    src: "{{download_dir}}/{{packages_url | basename}}"
    dest: "{{download_dir}}"
    extra_opts: "--strip-components=1"

- apt:
    deb: "{{download_dir}}/{{item}}_{{monetdb_version}}_{{packages_arch}}.deb"
  with_items: "{{ packages['deb'] if ansible_distribution_file_variety == 'Debian' else [] }}"
  become: true

- name: Start MonetDBD
  service:
    name: monetdbd
    state: started
    enabled: yes
  become: true
