---

# This set of tasks downloads and installs MonetDB for Exanest and TPC-H scale
# factor 1 in a server running Centos 7 prepared earlier

# It assumes that there is a user exanest capable of using sudo and that the
# current user is able to ssh without a password.

# Author: Panagiotis Koutsourakis <kutsurak@monetdbsolutions.com>

- name: Install MonetDB
  become: yes
  yum:
    name: "{{ download_dir }}/monetdb/rpms/{{ item }}-{{ monetdb_version }}.{{ system_spec }}.rpm"
    state: present
  with_items: "{{ packages }}"
  # notify: restart monetdb daemon

- name: Start monetdb daemon
  become: yes
  service:
    name: monetdbd
    state: started
    enabled: yes

- name: Install sysstats
  become: yes
  yum:
    name: sysstat
    state: present

- name: Add user exanest to the monetdb group
  become: yes
  user:
    name: exanest
    groups: monetdb
    append: yes

- name: Upload dotmonetdb file
  copy:
    src: files/dotmonetdb
    dest: /home/exanest/.monetdb
    owner: exanest
    group: exanest
    mode: 0644

- name: Wait for monetdb to come up
  wait_for:
    port: 50000
    search_regex: merovingian
