# Variables for the monetdb node role

# Author: Panagiotis Koutsourakis <kutsurak@monetdbsolutions.com>

ansible_become_pass: exanest
packages:
  - MonetDB-stream
  - MonetDB
  - MonetDB-client
  - MonetDB5-server
  - MonetDB-SQL-server5
  - MonetDB5-server-hugeint
  - MonetDB-SQL-server5-hugeint
